schema: 1

bugzilla:
  product: Core
  component: "General"

origin:
  name: wasm2c_sandbox_compiler
  description: wasm2c fork used for rlbox sandboxing
  url: https://github.com/PLSysSec/wasm2c_sandbox_compiler

  release: commit 8b0e6e8c96d534698bf8c2cf0c860883ec2b7d34 (2021-08-04T21:00:09Z).
  revision: 8b0e6e8c96d534698bf8c2cf0c860883ec2b7d34

  license: Apache-2.0
  license-file: LICENSE

vendoring:
  url: https://github.com/PLSysSec/wasm2c_sandbox_compiler.git
  source-hosting: github
  vendor-directory: third_party/wasm2c

  # ideally we would have exclude *, and the explicitly include certain folders, but this does not work
  # so just explicitly exclude what we don't want for now
  exclude:
    # dirs
    - .github
    - cmake
    - docs
    - fuzz-in
    - man
    - scripts
    - test
    - third_party
    - src/interp
    - wasm2c/examples
    # files
    - .clang-format
    - .flake8
    - .gitattributes
    - .gitignore
    - .gitmodules
    - .style.yapf
    - CMakeLists.txt
    - Contributing.md
    - Makefile
    - README.md
    - ubsan.blacklist
