#!/bin/sh

./mach package
tar --strip-components=1 -xvf  obj-x86_64-pc-linux-gnu/dist/*.tar.bz2 -C datcord.AppImage/usr/bin/
mv datcord.AppImage/usr/bin/firefox datcord.AppImage/usr/bin/datcord 
mv datcord.AppImage/usr/bin/firefox-bin datcord.AppImage/usr/bin/datcord-bin 
ARCH=x86_64 appimagetool datcord.AppImage/