#!/bin/sh

origLocation=$PWD
here="$(dirname "$(readlink -f "${0}")")"
export MOZ_LEGACY_PROFILES=1
export SNAP_NAME="firefox"
bin="${here}/usr/bin/datcord"
argv=$@
argc="$#"

cd ${here}/usr/bin/
cp ${here}/usr/bin/open-in-default-browser /tmp/open-in-default-browser

if [ $argc -eq 0 ] ; then
	$bin
else
	$bin $argv
fi

cd ${origLocation}
rm /tmp/open-in-default-browser