#!/bin/sh

origLocation=$PWD
here="$(dirname "$(readlink -f "${0}")")"
export MOZ_LEGACY_PROFILES=1
export SNAP_NAME="firefox"
bin="${here}/usr/bin/datcord"
argv=$@
argc="$#"

cd ${here}

if [ $argc -eq 0 ] ; then
	$bin
else
	$bin $argv
fi

cd ${origLocation}
