name: Update Submodules

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  push:
    branches: [ "neutron", "master", "unstable" ]
#  pull_request:
#    branches: [ "master" ]
    
jobs:
  # This workflow contains a single job called "update"
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Update Submodules
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
          git config --global user.name 'Submodule Updater'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Update Submodules" && git push || echo "No changes to commit"
          
