name: Update Submodules

# Controls when the action will run.
on:
  push:
#    branches: [ "neutron", "master", "unstable" ]
#  pull_request:
#    branches: [ "master" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "update"
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Update Submodules
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
          git config --global user.name 'Submodule Updater'
          git config --global user.email 'bot@noreply.github.com'
          git commit -am "Update Submodules"
      
      - name: GitHub Push
        # You may pin to the exact commit or the version.
        # uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        uses: ad-m/github-push-action@v0.6.0
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.TOKEN }}
