name: Update Submodules

# Controls when the action will run.
on:
  push:
#    branches: [ "neutron", "master", "unstable" ]
#  pull_request:
#    branches: [ "master" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "update"
  update:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: runsascoded/update-submodules@v1
        with:
          token: ${{ secrets.TOKEN }}
      - run: echo "Pushed new commit ${{ steps.update.outputs.sha }} with updated submodules"
